target-version = "py313"
exclude = [
    ".venv",
    ".eggs",
    ".git",
]
respect-gitignore = false # https://github.com/astral-sh/ruff/issues/9381
[lint]
select = [
    "B",
    "C",
    "E",
    "W",
    "F",
    "FLY",
    "DJ",
    "I",
    "N",
    "S",
    "PLC",
    "RUF",
    "UP",
]


[lint.isort]
known-first-party = ["apps"]
section-order = [
    "future",
    "standard-library",
    "third-party",

    "first-party",
    "local-folder"
]
